package com.hjn123.myandroidcodeback.pojo;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.consumer_id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer consumerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.object_to
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer objectTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.date
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.consumer_id
     *
     * @return the value of comment.consumer_id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getConsumerId() {
        return consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.consumer_id
     *
     * @param consumerId the value for comment.consumer_id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setConsumerId(Integer consumerId) {
        this.consumerId = consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.object_to
     *
     * @return the value of comment.object_to
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getObjectTo() {
        return objectTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.object_to
     *
     * @param objectTo the value for comment.object_to
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setObjectTo(Integer objectTo) {
        this.objectTo = objectTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.date
     *
     * @return the value of comment.date
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.date
     *
     * @param date the value for comment.date
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}