package com.hjn123.myandroidcodeback.pojo;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class Consumer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer_ord.id
     *
     * @mbg.generated Sun May 03 13:11:35 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer_ord.username
     *
     * @mbg.generated Sun May 03 13:11:35 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer_ord.password
     *
     * @mbg.generated Sun May 03 13:11:35 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer_ord.phone
     *
     * @mbg.generated Sun May 03 13:11:35 CST 2020
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer_ord.id
     *
     * @return the value of consumer_ord.id
     *
     * @mbg.generated Sun May 03 13:11:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer_ord.id
     *
     * @param id the value for consumer_ord.id
     *
     * @mbg.generated Sun May 03 13:11:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer_ord.username
     *
     * @return the value of consumer_ord.username
     *
     * @mbg.generated Sun May 03 13:11:35 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer_ord.username
     *
     * @param username the value for consumer_ord.username
     *
     * @mbg.generated Sun May 03 13:11:35 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer_ord.password
     *
     * @return the value of consumer_ord.password
     *
     * @mbg.generated Sun May 03 13:11:35 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer_ord.password
     *
     * @param password the value for consumer_ord.password
     *
     * @mbg.generated Sun May 03 13:11:35 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer_ord.phone
     *
     * @return the value of consumer_ord.phone
     *
     * @mbg.generated Sun May 03 13:11:35 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer_ord.phone
     *
     * @param phone the value for consumer_ord.phone
     *
     * @mbg.generated Sun May 03 13:11:35 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}