package com.hjn123.myandroidcodeback.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class ConsumerSendToBox {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_send_order.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_send_order.user_id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_send_order.express_id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer expressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_send_order.order_no
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Long orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_send_order.payment
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private BigDecimal payment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_send_order.status
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_send_order.payment_time
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Date paymentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_send_order.create_time
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_send_order.id
     *
     * @return the value of express_send_order.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_send_order.id
     *
     * @param id the value for express_send_order.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_send_order.user_id
     *
     * @return the value of express_send_order.user_id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_send_order.user_id
     *
     * @param userId the value for express_send_order.user_id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_send_order.express_id
     *
     * @return the value of express_send_order.express_id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getExpressId() {
        return expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_send_order.express_id
     *
     * @param expressId the value for express_send_order.express_id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setExpressId(Integer expressId) {
        this.expressId = expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_send_order.order_no
     *
     * @return the value of express_send_order.order_no
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_send_order.order_no
     *
     * @param orderNo the value for express_send_order.order_no
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_send_order.payment
     *
     * @return the value of express_send_order.payment
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_send_order.payment
     *
     * @param payment the value for express_send_order.payment
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_send_order.status
     *
     * @return the value of express_send_order.status
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_send_order.status
     *
     * @param status the value for express_send_order.status
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_send_order.payment_time
     *
     * @return the value of express_send_order.payment_time
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_send_order.payment_time
     *
     * @param paymentTime the value for express_send_order.payment_time
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_send_order.create_time
     *
     * @return the value of express_send_order.create_time
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_send_order.create_time
     *
     * @param createTime the value for express_send_order.create_time
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}