package com.hjn123.myandroidcodeback.pojo;

import java.util.Date;

public class CourierSendToBox {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier_send_express.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier_send_express.code
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier_send_express.track_no
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private String trackNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier_send_express.courier_id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer courierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier_send_express.re_phone
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private String rePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier_send_express.save_time
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Date saveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier_send_express.box_id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer boxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier_send_express.is_pick
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Boolean isPick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier_send_express.is_delay
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Boolean isDelay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier_send_express.delay_day
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer delayDay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier_send_express.id
     *
     * @return the value of courier_send_express.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier_send_express.id
     *
     * @param id the value for courier_send_express.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier_send_express.code
     *
     * @return the value of courier_send_express.code
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier_send_express.code
     *
     * @param code the value for courier_send_express.code
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier_send_express.track_no
     *
     * @return the value of courier_send_express.track_no
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public String getTrackNo() {
        return trackNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier_send_express.track_no
     *
     * @param trackNo the value for courier_send_express.track_no
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setTrackNo(String trackNo) {
        this.trackNo = trackNo == null ? null : trackNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier_send_express.courier_id
     *
     * @return the value of courier_send_express.courier_id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getCourierId() {
        return courierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier_send_express.courier_id
     *
     * @param courierId the value for courier_send_express.courier_id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setCourierId(Integer courierId) {
        this.courierId = courierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier_send_express.re_phone
     *
     * @return the value of courier_send_express.re_phone
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public String getRePhone() {
        return rePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier_send_express.re_phone
     *
     * @param rePhone the value for courier_send_express.re_phone
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setRePhone(String rePhone) {
        this.rePhone = rePhone == null ? null : rePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier_send_express.save_time
     *
     * @return the value of courier_send_express.save_time
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Date getSaveTime() {
        return saveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier_send_express.save_time
     *
     * @param saveTime the value for courier_send_express.save_time
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setSaveTime(Date saveTime) {
        this.saveTime = saveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier_send_express.box_id
     *
     * @return the value of courier_send_express.box_id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getBoxId() {
        return boxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier_send_express.box_id
     *
     * @param boxId the value for courier_send_express.box_id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setBoxId(Integer boxId) {
        this.boxId = boxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier_send_express.is_pick
     *
     * @return the value of courier_send_express.is_pick
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Boolean getIsPick() {
        return isPick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier_send_express.is_pick
     *
     * @param isPick the value for courier_send_express.is_pick
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setIsPick(Boolean isPick) {
        this.isPick = isPick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier_send_express.is_delay
     *
     * @return the value of courier_send_express.is_delay
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Boolean getIsDelay() {
        return isDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier_send_express.is_delay
     *
     * @param isDelay the value for courier_send_express.is_delay
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setIsDelay(Boolean isDelay) {
        this.isDelay = isDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier_send_express.delay_day
     *
     * @return the value of courier_send_express.delay_day
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getDelayDay() {
        return delayDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier_send_express.delay_day
     *
     * @param delayDay the value for courier_send_express.delay_day
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setDelayDay(Integer delayDay) {
        this.delayDay = delayDay;
    }
}