package com.hjn123.myandroidcodeback.pojo;

public class Courier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier.name
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier.password
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier.phone
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier.id_card
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier.company
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer company;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier.id
     *
     * @return the value of courier.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier.id
     *
     * @param id the value for courier.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier.name
     *
     * @return the value of courier.name
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier.name
     *
     * @param name the value for courier.name
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier.password
     *
     * @return the value of courier.password
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier.password
     *
     * @param password the value for courier.password
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier.phone
     *
     * @return the value of courier.phone
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier.phone
     *
     * @param phone the value for courier.phone
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier.id_card
     *
     * @return the value of courier.id_card
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier.id_card
     *
     * @param idCard the value for courier.id_card
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier.company
     *
     * @return the value of courier.company
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier.company
     *
     * @param company the value for courier.company
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setCompany(Integer company) {
        this.company = company;
    }
}