package com.hjn123.myandroidcodeback.pojo;

public class ExpressBox {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_box.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_box.name
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_box.cabinet_from
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer cabinetFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_box.size
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_box.is_using
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Byte isUsing;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_box.id
     *
     * @return the value of express_box.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_box.id
     *
     * @param id the value for express_box.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_box.name
     *
     * @return the value of express_box.name
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_box.name
     *
     * @param name the value for express_box.name
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_box.cabinet_from
     *
     * @return the value of express_box.cabinet_from
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getCabinetFrom() {
        return cabinetFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_box.cabinet_from
     *
     * @param cabinetFrom the value for express_box.cabinet_from
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setCabinetFrom(Integer cabinetFrom) {
        this.cabinetFrom = cabinetFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_box.size
     *
     * @return the value of express_box.size
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_box.size
     *
     * @param size the value for express_box.size
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_box.is_using
     *
     * @return the value of express_box.is_using
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Byte getIsUsing() {
        return isUsing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_box.is_using
     *
     * @param isUsing the value for express_box.is_using
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setIsUsing(Byte isUsing) {
        this.isUsing = isUsing;
    }
}