package com.hjn123.myandroidcodeback.pojo;

public class ExpressCabinet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_cabinet.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_cabinet.name
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_cabinet.address
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_cabinet.bigbox
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer bigbox;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_cabinet.middlebox
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer middlebox;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_cabinet.smallbox
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer smallbox;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_cabinet.id
     *
     * @return the value of express_cabinet.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_cabinet.id
     *
     * @param id the value for express_cabinet.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_cabinet.name
     *
     * @return the value of express_cabinet.name
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_cabinet.name
     *
     * @param name the value for express_cabinet.name
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_cabinet.address
     *
     * @return the value of express_cabinet.address
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_cabinet.address
     *
     * @param address the value for express_cabinet.address
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_cabinet.bigbox
     *
     * @return the value of express_cabinet.bigbox
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getBigbox() {
        return bigbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_cabinet.bigbox
     *
     * @param bigbox the value for express_cabinet.bigbox
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setBigbox(Integer bigbox) {
        this.bigbox = bigbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_cabinet.middlebox
     *
     * @return the value of express_cabinet.middlebox
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getMiddlebox() {
        return middlebox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_cabinet.middlebox
     *
     * @param middlebox the value for express_cabinet.middlebox
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setMiddlebox(Integer middlebox) {
        this.middlebox = middlebox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_cabinet.smallbox
     *
     * @return the value of express_cabinet.smallbox
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getSmallbox() {
        return smallbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_cabinet.smallbox
     *
     * @param smallbox the value for express_cabinet.smallbox
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setSmallbox(Integer smallbox) {
        this.smallbox = smallbox;
    }
}