package com.hjn123.myandroidcodeback.pojo;

public class ExpressCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_company.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_company.company_name
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private String companyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_company.id
     *
     * @return the value of express_company.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_company.id
     *
     * @param id the value for express_company.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_company.company_name
     *
     * @return the value of express_company.company_name
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_company.company_name
     *
     * @param companyName the value for express_company.company_name
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }
}