package com.hjn123.myandroidcodeback.pojo;

public class SendExpressDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_express.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_express.send_name
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private String sendName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_express.send_phone
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private String sendPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_express.send_address
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private String sendAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_express.recive_name
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private String reciveName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_express.recive_phone
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private String recivePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_express. recive_address
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private String reciveAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_express.cabinet_id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer cabinetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_express.company
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Integer company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_express.is_save
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private Byte isSave;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_express.detail
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_express.id
     *
     * @return the value of send_express.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_express.id
     *
     * @param id the value for send_express.id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_express.send_name
     *
     * @return the value of send_express.send_name
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public String getSendName() {
        return sendName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_express.send_name
     *
     * @param sendName the value for send_express.send_name
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setSendName(String sendName) {
        this.sendName = sendName == null ? null : sendName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_express.send_phone
     *
     * @return the value of send_express.send_phone
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public String getSendPhone() {
        return sendPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_express.send_phone
     *
     * @param sendPhone the value for send_express.send_phone
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setSendPhone(String sendPhone) {
        this.sendPhone = sendPhone == null ? null : sendPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_express.send_address
     *
     * @return the value of send_express.send_address
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public String getSendAddress() {
        return sendAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_express.send_address
     *
     * @param sendAddress the value for send_express.send_address
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setSendAddress(String sendAddress) {
        this.sendAddress = sendAddress == null ? null : sendAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_express.recive_name
     *
     * @return the value of send_express.recive_name
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public String getReciveName() {
        return reciveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_express.recive_name
     *
     * @param reciveName the value for send_express.recive_name
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setReciveName(String reciveName) {
        this.reciveName = reciveName == null ? null : reciveName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_express.recive_phone
     *
     * @return the value of send_express.recive_phone
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public String getRecivePhone() {
        return recivePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_express.recive_phone
     *
     * @param recivePhone the value for send_express.recive_phone
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setRecivePhone(String recivePhone) {
        this.recivePhone = recivePhone == null ? null : recivePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_express. recive_address
     *
     * @return the value of send_express. recive_address
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public String getReciveAddress() {
        return reciveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_express. recive_address
     *
     * @param reciveAddress the value for send_express. recive_address
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setReciveAddress(String reciveAddress) {
        this.reciveAddress = reciveAddress == null ? null : reciveAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_express.cabinet_id
     *
     * @return the value of send_express.cabinet_id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getCabinetId() {
        return cabinetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_express.cabinet_id
     *
     * @param cabinetId the value for send_express.cabinet_id
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setCabinetId(Integer cabinetId) {
        this.cabinetId = cabinetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_express.company
     *
     * @return the value of send_express.company
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Integer getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_express.company
     *
     * @param company the value for send_express.company
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setCompany(Integer company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_express.is_save
     *
     * @return the value of send_express.is_save
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public Byte getIsSave() {
        return isSave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_express.is_save
     *
     * @param isSave the value for send_express.is_save
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setIsSave(Byte isSave) {
        this.isSave = isSave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_express.detail
     *
     * @return the value of send_express.detail
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_express.detail
     *
     * @param detail the value for send_express.detail
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}