package com.hjn123.myandroidcodeback.dao;

import com.hjn123.myandroidcodeback.pojo.Consumer;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ConsumerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_ord
     *
     * @mbg.generated Sun May 03 13:11:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_ord
     *
     * @mbg.generated Sun May 03 13:11:35 CST 2020
     */
    int insert(Consumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_ord
     *
     * @mbg.generated Sun May 03 13:11:35 CST 2020
     */
    Consumer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_ord
     *
     * @mbg.generated Sun May 03 13:11:35 CST 2020
     */
    List<Consumer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_ord
     *
     * @mbg.generated Sun May 03 13:11:35 CST 2020
     */
    int updateByPrimaryKey(Consumer record);

    /**
     * 判断用户名是否存在
     * select count(*) from user where username=xxx;
     */
    Integer findByUsername(@Param("username") String username);
    /**
     * 根据用户名和密码去查询
     */
    Consumer findByUsernameAndPassword(@Param("username") String username,@Param("password") String password);

    /**
     * 判断用户手机号是否存在
     * select count(*) from user where username=xxx;
     */
    Integer findByPhone(@Param("phone") String phone);
}