package com.hjn123.myandroidcodeback.dao;

import com.hjn123.myandroidcodeback.pojo.ConsumerSendToBox;
import java.util.List;

public interface ConsumerSendToBoxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_send_order
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_send_order
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int insert(ConsumerSendToBox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_send_order
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    ConsumerSendToBox selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_send_order
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    List<ConsumerSendToBox> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_send_order
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int updateByPrimaryKey(ConsumerSendToBox record);
}