package com.hjn123.myandroidcodeback.dao;

import com.hjn123.myandroidcodeback.pojo.Courier;
import java.util.List;

public interface CourierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int insert(Courier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    Courier selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    List<Courier> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int updateByPrimaryKey(Courier record);
}