package com.hjn123.myandroidcodeback.dao;

import com.hjn123.myandroidcodeback.pojo.CourierSendToBox;
import java.util.List;

public interface CourierSendToBoxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier_send_express
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier_send_express
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int insert(CourierSendToBox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier_send_express
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    CourierSendToBox selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier_send_express
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    List<CourierSendToBox> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier_send_express
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int updateByPrimaryKey(CourierSendToBox record);
}