package com.hjn123.myandroidcodeback.dao;

import com.hjn123.myandroidcodeback.pojo.ExpressCabinet;
import java.util.List;

public interface ExpressCabinetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_cabinet
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_cabinet
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int insert(ExpressCabinet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_cabinet
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    ExpressCabinet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_cabinet
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    List<ExpressCabinet> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_cabinet
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int updateByPrimaryKey(ExpressCabinet record);
}