package com.hjn123.myandroidcodeback.dao;

import com.hjn123.myandroidcodeback.pojo.ExpressBox;
import java.util.List;

public interface ExpressBoxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_box
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_box
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int insert(ExpressBox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_box
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    ExpressBox selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_box
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    List<ExpressBox> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_box
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int updateByPrimaryKey(ExpressBox record);
}