package com.hjn123.myandroidcodeback.dao;

import com.hjn123.myandroidcodeback.pojo.RentBox;
import java.util.List;

public interface RentBoxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier_rent_box
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier_rent_box
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int insert(RentBox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier_rent_box
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    RentBox selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier_rent_box
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    List<RentBox> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier_rent_box
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int updateByPrimaryKey(RentBox record);
}