package com.hjn123.myandroidcodeback.dao;

import com.hjn123.myandroidcodeback.pojo.SendExpressDetail;
import java.util.List;

public interface SendExpressDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_express
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_express
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int insert(SendExpressDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_express
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    SendExpressDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_express
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    List<SendExpressDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_express
     *
     * @mbg.generated Mon May 04 16:20:14 CST 2020
     */
    int updateByPrimaryKey(SendExpressDetail record);
}